# Generated by Django 5.2.4 on 2025-08-30 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_membership',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
